// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaSGvsJ-81sax_0tv3lZA6jHy2C6SZtpU',
    appId: '1:160812335149:web:0615a47f022e06edcd38a4',
    messagingSenderId: '160812335149',
    projectId: 'course-hotelio-e18d3',
    authDomain: 'course-hotelio-e18d3.firebaseapp.com',
    storageBucket: 'course-hotelio-e18d3.appspot.com',
    measurementId: 'G-N0NSXX3Z22',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfFmjXK1MUA6qUAP-QR8hd9iU2UohUMgU',
    appId: '1:160812335149:android:312f16ecc1d3e1f5cd38a4',
    messagingSenderId: '160812335149',
    projectId: 'course-hotelio-e18d3',
    storageBucket: 'course-hotelio-e18d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpjJmayrZGjcm8RsBNj0srLbUmnveOJt4',
    appId: '1:160812335149:ios:00bfcbf29818dceccd38a4',
    messagingSenderId: '160812335149',
    projectId: 'course-hotelio-e18d3',
    storageBucket: 'course-hotelio-e18d3.appspot.com',
    iosClientId: '160812335149-eae3eba5ud32ng699o1c6p2jd0bv0l4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpjJmayrZGjcm8RsBNj0srLbUmnveOJt4',
    appId: '1:160812335149:ios:00bfcbf29818dceccd38a4',
    messagingSenderId: '160812335149',
    projectId: 'course-hotelio-e18d3',
    storageBucket: 'course-hotelio-e18d3.appspot.com',
    iosClientId: '160812335149-eae3eba5ud32ng699o1c6p2jd0bv0l4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.hotelio',
  );
}
